import React from "react";

const Privacy = () => {
  return (
    <>
      <main className="mt-10">
        <section 
          className="py-12 min-h-screen"
          style={{
            backgroundImage: "url('/background123.webp')",
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat"
          }}
        >
          <div className="container mx-auto px-4">
            <div className="p-8 bg-white/95 w-[90%] mx-auto">
              <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
              <p className="text-gray-600 mb-4">Last updated: May 23, 2025</p>
              
              <div className="prose prose-slate max-w-none">
                <p>
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p>
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
                
                <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>
                
                <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
                <p>
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                
                <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2 my-4">
                  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong>Application</strong> refers to Kolkata Business Club, the software program provided by the Company.</li>
                  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Kolkata Business Club.</li>
                  <li><strong>Country</strong> refers to: West Bengal, India</li>
                  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service</strong> refers to the Application.</li>
                  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                
                <h2 className="text-2xl font-bold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
                
                <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>
                
                <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
                <p>
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-2 my-4">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>
                
                <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
                <p>
                  Usage Data is collected automatically when using the Service.
                </p>
                <p>
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>
                
                <h4 className="text-lg font-semibold mt-4 mb-2">Information Collected while Using the Application</h4>
                <p>
                  While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
                </p>
                <ul className="list-disc pl-6 space-y-2 my-4">
                  <li>Pictures and other information from your Device's camera and photo library</li>
                </ul>
                <p>
                  We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
                </p>
                <p>
                  You can enable or disable access to this information at any time, through Your Device settings.
                </p>
                
                <h3 className="text-xl font-semibold mt-6 mb-3">Use of Your Personal Data</h3>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2 my-4">
                  <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                  <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                  <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                  <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                  <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
                </ul>
                
                <h3 className="text-xl font-semibold mt-6 mb-3">Contact Us</h3>
                <p>
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <ul className="list-disc pl-6 space-y-2 my-4">
                  <li>By email: info@kolkatabusinessclub.com</li>
                  <li>By phone: +91 33 1234 5678</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Privacy;